# Generated by Django 4.1.7 on 2023-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Web3User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('avatar', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('nonce', models.IntegerField()),
            ],
        ),
    ]
